--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SantanasWrld/Claims
build-by-default: true
branches:
- main
projects:
  Claims:
    path: ""
    icon: "icon.png"
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
